Update radio-stream-capture.yml

diff --git a/.github/workflows/radio-stream-capture.yml b/.github/workflows/radio-stream-capture.yml
--- a/.github/workflows/radio-stream-capture.yml
+++ b/.github/workflows/radio-stream-capture.yml
@@ -68,8 +68,21 @@ jobs:
 
       - name: Convert m3u8 to m4a
         run: |
-            chmod +x scripts/download.sh
-            scripts/download.sh
+            json_file="scripts/temp.json"
+            if ! command -v jq &> /dev/null; then
+                echo "jq command not found. Install jq like sudo apt-get install -y jq"
+                exit 1
+            fi
+            jq -c '.[]' "$json_file" | while IFS= read -r entry; do
+                url=$(echo "$entry" | jq -r '.streaming_url')
+                path=$(echo "$entry" | jq -r '.audio_path')
+                if [[ -n "$url" && -n "$path" ]]; then
+                    echo "ffmpeg -http_seekable 0 -i \"$url\" -loglevel quiet -ab 46k -ac 2 -ar 24000 -write_xing 0 \"$path\""
+                    ffmpeg -http_seekable 0 -i "$url" -loglevel quiet -ab 46k -ac 2 -ar 24000 -write_xing 0 "$path"
+                else
+                    echo "Error: URL or PATH not found"
+                fi
+            done
 
       - name: auto-commit-changes
         run: |
