Update WG_VPN_Test.yml

diff --git a/.github/workflows/WG_VPN_Test.yml b/.github/workflows/WG_VPN_Test.yml
--- a/.github/workflows/WG_VPN_Test.yml
+++ b/.github/workflows/WG_VPN_Test.yml
@@ -26,14 +26,29 @@ jobs:
           sudo chmod 600 /etc/wireguard/wg0.conf
 
       - name: Start WireGuard VPN
-        run: sudo wg-quick up wg0
+        run: |
+          sudo wg-quick up wg0
+          sleep 20
 
-      - name: Check connection and country
+      - name: Verify VPN Connection
         run: |
           sudo wg
+          sleep 10
+
+      - name: Check external IP and country
+        run: |
           IP=$(curl -s http://ifconfig.me)
+          if [ -z "$IP" ]; then
+            echo "Failed to retrieve external IP address."
+            exit 1
+          fi
           echo "IP Address: $IP"
+          
           COUNTRY=$(curl -s https://ipinfo.io/${IP}/country)
+          if [ -z "$COUNTRY" ]; then
+            echo "Failed to retrieve country code."
+            exit 1
+          fi
           echo "Country Code: $COUNTRY"
 
       - name: End WireGuard VPN
